### ISSUE TITLE
"unkown location"

### ISSUE THREAD

**Issue by jayrajkharvadi** [stuarta0/blender-photogrammetry#14]
Hello Stuart,

many thanks for creating this addon. 
I used for a couple of projects. 
Now, suddenly it has stopped working. 

I have tried using it with Colmap, PMVS, visualSFM .
I also tried using it across different versions of blender (2.8, 2.81, 2.90.1, 2.91 beta, 2.92 )

Specs : 
OS : windows  10
Processor : intel i7 7700
Graphics card : 1070 mobile.

Can you help me please? Console output below. 
Thanks,
Jayraj

This is what is output in the console window.
------------------------------------------------------------------------------------------------------------------------------

Modules Installed (blender_photogrammetry) from 'D:\\Softwares\\Blender_Addons\\blender-photogrammetry-1.1-windows.zip' into 'C:\\Users\\J\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\addons'
Problem importing photogrammetry module "openmvs": Attributes "importer" and/or "exporter" must be defined in module
Problem importing photogrammetry module "__pycache__": Attributes "importer" and/or "exporter" must be defined in module
Warning: class PHOTOGRAMMETRY_PT_preferences contains a property which should be an annotation!
C:\Users\J\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender_photogrammetry\__init__.py:184
    assign as a type annotation: PHOTOGRAMMETRY_PT_preferences.collection_name
Warning: class PHOTOGRAMMETRY_PG_master contains a property which should be an annotation!
C:\Users\J\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender_photogrammetry\__init__.py:184
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.input
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.output
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.in_blender
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.in_bundler
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.in_colmap
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.in_imagemodeler
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.in_meshroom
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.in_visualsfm
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.out_blender
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.out_bundler
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.out_colmap
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.out_pmvs
    assign as a type annotation: PHOTOGRAMMETRY_PG_master.out_visualsfm
[blender-photogrammetry] Platform: windows
process photogrammetry
in_blender
out_colmap

**Comment by stuarta0** [comment]
Was there any more console output? Usually `<unknown location>` is accompanied with a stack trace. e.g.

```
process photogrammetry
in_bundler
out_bundler
Traceback (most recent call last):
  File "/home/stuart/.config/blender/2.90/scripts/addons/blender_photogrammetry/__init__.py", line 88, in execute
    data = inputs[p.input].func(extract_props, scene=scene)
  File "/home/stuart/.config/blender/2.90/scripts/addons/blender_photogrammetry/bundler/extract.py", line 14, in extract
    with open(os.path.join(dirpath, 'bundle.out'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'bundler/bundle.out'

location: <unknown location>:-1
```

**Comment by stuarta0** [comment]
I've made some code changes in the master branch for better feedback from known issues (e.g. properties with missing or incorrect values), and changes to get rid of the type annotation warnings on startup.

It may not relate directly to your issue, but is easier to identify unhandled exceptions.

**Comment by jayrajkharvadi** [comment]
Thanks for the response Stuart and apology for the late reply. 
I removed the previous installed version of the addon and I installed the latest version from master (1.2.0) on blender 2.90.1. 

Hope this helps. 

**Here is the output from the window console.** 

_Modules Installed (blender-photogrammetry-master) from 'D:\\Softwares\\Blender_Addons\\blender-photogrammetry\\blender-photogrammetry-master_18Nov2020.zip' into 'C:\\Users\\J\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons'
module changed on disk: 'C:\\Users\\J\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons\\blender-photogrammetry-master\\__init__.py' reloading...
Problem importing photogrammetry module "openmvs": Attributes "importer" and/or "exporter" must be defined in module
Problem importing photogrammetry module "__pycache__": Attributes "importer" and/or "exporter" must be defined in module
[blender-photogrammetry] Platform: windows
process photogrammetry
in_blender
out_colmap
Saved: 'D:\Work\projects\t-rex\work\shot20_photogrammetryTest\renderoutput\photogrammetry\1001.jpg'
 Time: 00:03.27 (Saving: 00:01.66)

Saved: 'D:\Work\projects\t-rex\work\shot20_photogrammetryTest\renderoutput\photogrammetry\1006.jpg'
 Time: 00:13.39 (Saving: 00:12.19)

Saved: 'D:\Work\projects\t-rex\work\shot20_photogrammetryTest\renderoutput\photogrammetry\1011.jpg'
 Time: 00:02.48 (Saving: 00:01.05)

Saved: 'D:\Work\projects\t-rex\work\shot20_photogrammetryTest\renderoutput\photogrammetry\1016.jpg'
 Time: 00:02.39 (Saving: 00:01.24)

Saved: 'D:\Work\projects\t-rex\work\shot20_photogrammetryTest\renderoutput\photogrammetry\1021.jpg'
 Time: 00:02.47 (Saving: 00:01.06)

Saved: 'D:\Work\projects\t-rex\work\shot20_photogrammetryTest\renderoutput\photogrammetry\1026.jpg'
 Time: 00:02.34 (Saving: 00:01.04)

Saved: 'D:\Work\projects\t-rex\work\shot20_photogrammetryTest\renderoutput\photogrammetry\1031.jpg'
 Time: 00:02.34 (Saving: 00:01.05)

Saved: 'D:\Work\projects\t-rex\work\shot20_photogrammetryTest\renderoutput\photogrammetry\1036.jpg'
 Time: 00:02.32 (Saving: 00:01.05)

Saved: 'D:\Work\projects\t-rex\work\shot20_photogrammetryTest\renderoutput\photogrammetry\1041.jpg'
 Time: 00:02.27 (Saving: 00:01.08)

{'cameras': {}, 'resolution': (4096, 2304), 'trackers': {}}
"C:\Users\J\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-photogrammetry-master\colmap\windows\colmap.exe" image_undistorter --image_path D:\Work\projects\t-rex\work\shot20_photogrammetryTest\colmap\images --input_path D:\Work\projects\t-rex\work\shot20_photogrammetryTest\colmap\sparse --output_path D:\Work\projects\t-rex\work\shot20_photogrammetryTest\colmap\dense --output_type COLMAP --max_image_size 500

==============================================================================
Image undistortion
==============================================================================

Writing reconstruction...
Writing configuration...
Writing scripts...
Elapsed time: 0.000 [minutes]
"C:\Users\J\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-photogrammetry-master\colmap\windows\colmap.exe" patch_match_stereo --workspace_path D:\Work\projects\t-rex\work\shot20_photogrammetryTest\colmap\dense
Reading workspace...
Reading configuration...
Configuration has 0 problems...
Elapsed time: 0.000 [minutes]
"C:\Users\J\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-photogrammetry-master\colmap\windows\colmap.exe" stereo_fusion --workspace_path D:\Work\projects\t-rex\work\shot20_photogrammetryTest\colmap\dense --output_path D:\Work\projects\t-rex\work\shot20_photogrammetryTest\colmap\dense\fused.ply

StereoFusion::Options
---------------------
max_image_size: -1
min_num_pixels: 5
max_num_pixels: 10000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10
check_num_images: 50
cache_size: 32

Reading workspace...
Reading configuration...
Fusing image [1/0]Traceback (most recent call last):
  File "C:\Users\J\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-photogrammetry-master\__init__.py", line 100, in execute
    outputs[p.output].func(load_props, data, scene=scene)
  File "C:\Users\J\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-photogrammetry-master\colmap\load.py", line 243, in load
    print(subprocess.list2cmdline(cmd_args))
Exception: Command failed, see system console for details

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\J\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-photogrammetry-master\__init__.py", line 100, in execute
    outputs[p.output].func(load_props, data, scene=scene)
  File "C:\Users\J\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-photogrammetry-master\colmap\load.py", line 243, in load
    print(subprocess.list2cmdline(cmd_args))
Exception: Command failed, see system console for details

location: <unknown location>:-1_

**Comment by stuarta0** [comment]
Hi jayrajkharvadi - I've just had another look at your output. It looks like there wasn't a successful reconstruction from blender, so it eventually gets to a point in COLMAP that fails because it's working with 0 images: `Fusing image [1/0]` - i.e. no images.

Reading back through the log you'll see this output: `{'cameras': {}, 'resolution': (4096, 2304), 'trackers': {}}` meaning the data extracted from blender had no cameras or trackers. I should probably put a test case in for that scenario to inform the user that the input needs investigating. In this case, that you need to check that the motion tracker successfully solved the motion first.

**Comment by enilnacs** [comment]
I also have the same unknown location, but i have a track (?).
Look here:

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0000.jpg'
 Time: 00:01.87 (Saving: 00:00.79)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0015.jpg'
 Time: 00:01.90 (Saving: 00:00.78)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0030.jpg'
 Time: 00:01.85 (Saving: 00:00.76)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0045.jpg'
 Time: 00:01.86 (Saving: 00:00.77)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0060.jpg'
 Time: 00:01.84 (Saving: 00:00.76)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0075.jpg'
 Time: 00:01.84 (Saving: 00:00.77)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0090.jpg'
 Time: 00:01.85 (Saving: 00:00.76)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0105.jpg'
 Time: 00:01.83 (Saving: 00:00.77)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0120.jpg'
 Time: 00:01.87 (Saving: 00:00.80)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0135.jpg'
 Time: 00:01.88 (Saving: 00:00.78)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0150.jpg'
 Time: 00:01.85 (Saving: 00:00.78)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0165.jpg'
 Time: 00:01.96 (Saving: 00:00.81)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0180.jpg'
 Time: 00:01.96 (Saving: 00:00.85)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0195.jpg'
 Time: 00:02.05 (Saving: 00:00.84)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0210.jpg'
 Time: 00:02.05 (Saving: 00:00.92)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0225.jpg'
 Time: 00:01.88 (Saving: 00:00.77)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0240.jpg'
 Time: 00:01.88 (Saving: 00:00.79)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0255.jpg'
 Time: 00:01.86 (Saving: 00:00.77)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0270.jpg'
 Time: 00:01.89 (Saving: 00:00.80)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0285.jpg'
 Time: 00:01.92 (Saving: 00:00.80)

Saved: 'X:\Petrone Digital\Projects\Crystal Castle\blender\renderoutput\photogrammetry\0300.jpg'
 Time: 00:02.05 (Saving: 00:00.82)

{'cameras': {0: {'R': ((0.6858268976211548,
                        0.727681577205658,
                        -0.010999688878655434),
                       (-0.3174891471862793,
                        0.31275975704193115,
                        0.8951994180679321),
                       (0.6548603773117065,
                        -0.610459566116333,
                        0.4455300569534302)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0000.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.336137056350708,
                       -0.3733687400817871,
                       -11.25279426574707),
                 'trackers': {0: (-69.66819763183594, 80.16822338104248),
                              1: (1222.9621124267578, -157.24164962768555),
                              2: (1178.6183166503906, -50.99829912185669),
                              3: (1615.4319763183594, 234.52351570129395),
                              4: (71.84165954589844, 568.8303565979004),
                              5: (-91.76902770996094, -495.3192687034607),
                              6: (-629.1127395629883, -891.2798166275024),
                              7: (-1461.0528945922852, 3.0680179595947266),
                              8: (-1056.4698028564453, 647.8501653671265),
                              9: (-1682.4769592285156, 567.2863054275513),
                              (35 more)...}},
             1: {'R': ((0.6783493757247925,
                        0.7346707582473755,
                        -0.010050923563539982),
                       (-0.3211483061313629,
                        0.3087765574455261,
                        0.8952769637107849),
                       (0.6608372926712036,
                        -0.6040827035903931,
                        0.44539663195610046)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0015.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.3305172622203827,
                       -0.3749474287033081,
                       -11.255870819091797),
                 'trackers': {0: (-77.43965148925781, 79.3218469619751),
                              1: (1220.8804321289062, -165.62713623046875),
                              2: (1178.0033111572266, -58.48771333694458),
                              3: (1624.2716217041016, 226.37479305267334),
                              4: (69.98771667480469, 567.6631450653076),
                              5: (-111.48090362548828, -496.505663394928),
                              6: (-651.9814682006836, -886.6913723945618),
                              7: (-1451.7265319824219, 10.078239440917969),
                              8: (-1040.631980895996, 650.7759189605713),
                              9: (-1660.8634185791016, 572.340874671936),
                              (35 more)...}},
             2: {'R': ((0.6702436208724976,
                        0.7420844435691833,
                        -0.009174000471830368),
                       (-0.32502421736717224,
                        0.3046268820762634,
                        0.8952997922897339),
                       (0.6671826839447021,
                        -0.5970872044563293,
                        0.4453696608543396)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0030.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.3249036371707916,
                       -0.37400245666503906,
                       -11.258079528808594),
                 'trackers': {0: (-86.0269546508789, 79.28399562835693),
                              1: (1218.2913208007812, -173.59413385391235),
                              2: (1177.0195770263672, -65.65094947814941),
                              3: (1633.3966827392578, 218.49399089813232),
                              4: (67.99964904785156, 567.0001029968262),
                              5: (-132.50038146972656, -496.5000629425049),
                              6: (-677.0884323120117, -881.5624523162842),
                              7: (-1441.860122680664, 17.7059268951416),
                              8: (-1023.5665512084961, 654.2810297012329),
                              9: (-1638.0000686645508, 577.9993915557861),
                              (36 more)...}},
             3: {'R': ((0.6616376042366028,
                        0.7497801184654236,
                        -0.008090832270681858),
                       (-0.32897326350212097,
                        0.29996243119239807,
                        0.8954323530197144),
                       (0.6738043427467346,
                        -0.5897900462150574,
                        0.4451240599155426)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0045.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.31450405716896057,
                       -0.37658238410949707,
                       -11.260529518127441),
                 'trackers': {0: (-93.83720397949219, 78.54164600372314),
                              1: (1216.823501586914, -183.03353548049927),
                              2: (1177.2395324707031, -74.47706937789917),
                              3: (1643.9451599121094, 208.69925022125244),
                              4: (67.20130920410156, 565.5385780334473),
                              5: (-152.4184799194336, -497.40012645721436),
                              6: (-701.0890960693359, -876.0505771636963),
                              7: (-1430.8589172363281, 25.275936126708984),
                              8: (-1005.3220367431641, 657.3397779464722),
                              9: (-1613.5431289672852, 583.5538816452026),
                              (36 more)...}},
             4: {'R': ((0.6527560949325562,
                        0.7575372457504272,
                        -0.0068404460325837135),
                       (-0.33316805958747864,
                        0.2951708734035492,
                        0.8954737186431885),
                       (0.6803737878799438,
                        -0.5822469592094421,
                        0.4450618028640747)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0060.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.300642728805542,
                       -0.3776742219924927,
                       -11.263236999511719),
                 'trackers': {0: (-100.22712707519531, 78.09566974639893),
                              1: (1216.0993194580078, -192.7268886566162),
                              2: (1178.1891632080078, -83.17856311798096),
                              3: (1656.1063385009766, 198.91223430633545),
                              4: (67.5311279296875, 564.4358682632446),
                              5: (-171.5335464477539, -497.7234721183777),
                              6: (-723.4045028686523, -870.074508190155),
                              7: (-1418.6029815673828, 33.60116958618164),
                              8: (-985.9355163574219, 660.8703804016113),
                              9: (-1588.1552124023438, 589.5736598968506),
                              (36 more)...}},
             5: {'R': ((0.6436032652854919,
                        0.7653394341468811,
                        -0.005515798926353455),
                       (-0.33723658323287964,
                        0.2900499105453491,
                        0.8956241011619568),
                       (0.687056303024292,
                        -0.5745664238929749,
                        0.4447775185108185)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0075.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.2876952290534973,
                       -0.3818244934082031,
                       -11.265413284301758),
                 'trackers': {0: (-107.11910247802734, 76.82855129241943),
                              1: (1214.7651672363281, -203.30665826797485),
                              2: (1178.5961151123047, -92.8008484840393),
                              3: (1667.7021789550781, 187.89170265197754),
                              4: (67.68333435058594, 562.533130645752),
                              5: (-191.17721557617188, -498.5017418861389),
                              6: (-746.6706848144531, -864.5626974105835),
                              7: (-1406.5532684326172, 41.06019973754883),
                              8: (-966.5123748779297, 663.6435699462891),
                              9: (-1562.815933227539, 594.9985027313232),
                              (36 more)...}},
             6: {'R': ((0.6354085803031921,
                        0.7721632719039917,
                        -0.004451525863260031),
                       (-0.3406403958797455,
                        0.28547531366348267,
                        0.8958057761192322),
                       (0.692979097366333,
                        -0.5676863193511963,
                        0.44442346692085266)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0090.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.28549134731292725,
                       -0.3857461214065552,
                       -11.267061233520508),
                 'trackers': {0: (-116.56517028808594, 75.87982177734375),
                              1: (1210.353012084961, -212.33188390731812),
                              2: (1175.9843444824219, -101.23010873794556),
                              3: (1675.151596069336, 178.28956604003906),
                              4: (64.84725952148438, 560.7792234420776),
                              5: (-212.80872344970703, -499.1040802001953),
                              6: (-771.2758255004883, -859.2596483230591),
                              7: (-1398.0731964111328, 47.4913215637207),
                              8: (-950.8805465698242, 666.0137844085693),
                              9: (-1541.9451141357422, 599.481053352356),
                              (36 more)...}},
             7: {'R': ((0.6263439655303955,
                        0.7795372605323792,
                        -0.0038640927523374557),
                       (-0.3443368375301361,
                        0.2811086177825928,
                        0.8957734704017639),
                       (0.6993750333786011,
                        -0.5597317218780518,
                        0.4444940686225891)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0105.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.2701266407966614,
                       -0.384967565536499,
                       -11.267190933227539),
                 'trackers': {0: (-123.05007934570312, 76.15817070007324),
                              1: (1209.6199035644531, -220.8294439315796),
                              2: (1177.1292114257812, -108.85509252548218),
                              3: (1687.6657104492188, 169.61053848266602),
                              4: (64.70191955566406, 560.363245010376),
                              5: (-230.75340270996094, -498.24978590011597),
                              6: (-792.4625015258789, -852.8061246871948),
                              7: (-1385.2095794677734, 55.115790367126465),
                              8: (-931.8406677246094, 669.257025718689),
                              9: (-1517.3689270019531, 604.7674942016602),
                              (36 more)...}},
             8: {'R': ((0.6165673732757568,
                        0.7872964143753052,
                        -0.002994541311636567),
                       (-0.3483043313026428,
                        0.2761799991130829,
                        0.8957726955413818),
                       (0.7060656547546387,
                        -0.5512612462043762,
                        0.4445023238658905)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0120.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.24942907691001892,
                       -0.38445961475372314,
                       -11.267230033874512),
                 'trackers': {0: (-127.9324722290039, 76.15031719207764),
                              1: (1210.3193664550781, -229.9357795715332),
                              2: (1179.5077514648438, -117.06535577774048),
                              3: (1702.1255493164062, 159.89510536193848),
                              4: (66.43135070800781, 559.7153949737549),
                              5: (-247.44552612304688, -497.0973801612854),
                              6: (-812.9513168334961, -845.6040716171265),
                              7: (-1370.950698852539, 63.21340084075928),
                              8: (-910.8730316162109, 672.7029132843018),
                              9: (-1490.8454132080078, 610.430645942688),
                              (36 more)...}},
             9: {'R': ((0.6067094206809998,
                        0.794921338558197,
                        -0.0019374862313270569),
                       (-0.35237035155296326,
                        0.2711235284805298,
                        0.8957271575927734),
                       (0.7125579118728638,
                        -0.5427634119987488,
                        0.4445999264717102)),
                 'f': 2633,
                 'filename': 'X:\\Petrone Digital\\Projects\\Crystal '
                             'Castle\\blender\\renderoutput\\photogrammetry\\0135.jpg',
                 'k': (0.0, 0.0, 0.0),
                 'principal': (1920.0, 1080.0),
                 't': (-0.2303086370229721,
                       -0.3844696283340454,
                       -11.267257690429688),
                 'trackers': {0: (-133.45836639404297, 76.24945163726807),
                              1: (1209.836654663086, -239.7992706298828),
                              2: (1181.0584259033203, -126.09206199645996),
                              3: (1715.9053802490234, 149.47182655334473),
                              4: (68.17474365234375, 559.0390920639038),
                              5: (-264.9213409423828, -496.0269856452942),
                              6: (-833.5813522338867, -838.5429954528809),
                              7: (-1357.272720336914, 71.3761568069458),
                              8: (-890.4723358154297, 676.1041259765625),
                              9: (-1464.8309326171875, 616.4076805114746),
                              (35 more)...}},
             (11 more)...},
 'resolution': (3840, 2160),
 'trackers': {0: {'co': (2.2857608795166016,
                         -1.935935378074646,
                         2.1603286266326904),
                  'error': 0.5780784487724304,
                  'rgb': (0, 0, 0)},
              1: {'co': (4.887253761291504,
                         1.090054988861084,
                         1.2262614965438843),
                  'error': 0.3161816895008087,
                  'rgb': (0, 0, 0)},
              2: {'co': (4.558908462524414,
                         1.4427714347839355,
                         1.3478858470916748),
                  'error': 0.40321752429008484,
                  'rgb': (0, 0, 0)},
              3: {'co': (4.86846399307251,
                         4.273155212402344,
                         1.6473400592803955),
                  'error': 0.9537243247032166,
                  'rgb': (0, 0, 0)},
              4: {'co': (1.4266717433929443,
                         -0.5128611922264099,
                         3.1737542152404785),
                  'error': 0.5361977815628052,
                  'rgb': (0, 0, 0)},
              5: {'co': (3.683675765991211,
                         -3.291020393371582,
                         1.581945776939392),
                  'error': 1.4054185152053833,
                  'rgb': (0, 0, 0)},
              6: {'co': (3.5056443214416504,
                         -4.6582536697387695,
                         1.1882853507995605),
                  'error': 2.3529491424560547,
                  'rgb': (0, 0, 0)},
              7: {'co': (-4.197341442108154,
                         -4.17113733291626,
                         0.39694690704345703),
                  'error': 0.5132684111595154,
                  'rgb': (0, 0, 0)},
              8: {'co': (-9.303044319152832,
                         0.07832109928131104,
                         1.6756057739257812),
                  'error': 0.7234344482421875,
                  'rgb': (0, 0, 0)},
              9: {'co': (-11.847564697265625,
                         -2.9553513526916504,
                         1.2510740756988525),
                  'error': 0.770188570022583,
                  'rgb': (0, 0, 0)},
              (36 more)...}}
"C:\Users\master\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-photogrammetry-master\colmap\windows\colmap.exe" image_undistorter --image_path "X:\Petrone Digital\Projects\Crystal Castle\blender\colmap\images" --input_path "X:\Petrone Digital\Projects\Crystal Castle\blender\colmap\sparse" --output_path "X:\Petrone Digital\Projects\Crystal Castle\blender\colmap\dense" --output_type COLMAP --max_image_size 500

==============================================================================
Image undistortion
==============================================================================

Undistorting image [1/21]
Undistorting image [2/21]
Undistorting image [3/21]
Undistorting image [4/21]
Undistorting image [5/21]
Undistorting image [6/21]
Undistorting image [7/21]
Undistorting image [8/21]
Undistorting image [9/21]
Undistorting image [10/21]
Undistorting image [11/21]
Undistorting image [12/21]
Undistorting image [13/21]
Undistorting image [14/21]
Undistorting image [15/21]
Undistorting image [16/21]
Undistorting image [17/21]
Undistorting image [18/21]
Undistorting image [19/21]
Undistorting image [20/21]
Undistorting image [21/21]
Writing reconstruction...
Writing configuration...
Writing scripts...
Elapsed time: 0.101 [minutes]
"C:\Users\master\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-photogrammetry-master\colmap\windows\colmap.exe" patch_match_stereo --workspace_path "X:\Petrone Digital\Projects\Crystal Castle\blender\colmap\dense"
Reading workspace...
Reading configuration...
Configuration has 21 problems...

==============================================================================
Processing view 2 / 21
==============================================================================


==============================================================================
Processing view 1 / 21
==============================================================================
Reading inputs...


PatchMatch::Problem
-------------------
ref_image_idx: 2
src_image_idxs: 7 0 6 8 4 5 10 11 12 13 14 9 15 16 17 18 19 20

PatchMatchOptions
-----------------
max_image_size: -1
gpu_index: 1
depth_min: 4.19699
depth_max: 25.2422
window_radius: 5
window_step: 1
sigma_spatial: 5
sigma_color: 0.2
num_samples: 15
ncc_sigma: 0.6
min_triangulation_angle: 1
incident_angle_sigma: 0.9
num_iterations: 5
geom_consistency: Reading inputs...
0
geom_consistency_regularizer: 0.3
geom_consistency_max_cost: 3
filter: 0
filter_min_ncc: 0.1
filter_min_triangulation_angle: 3
filter_min_num_consistent: 2
filter_geom_consistency_max_cost: 1
write_consistency_graph: 0

PatchMatch::Run
---------------

PatchMatch::Problem
-------------------
ref_image_idx: 1
src_image_idxs: 5 6 3 0 7 4 8 9 10 11 12 13 14 15 16 17 18 19 20

PatchMatchOptions
-----------------
max_image_size: -1
gpu_index: 0
depth_min: 4.188
depth_max: 25.1135
window_radius: 5
window_step: 1
sigma_spatial: 5
sigma_color: 0.2
num_samples: 15
ncc_sigma: 0.6
min_triangulation_angle: 1
incident_angle_sigma: 0.9
num_iterations: 5
geom_consistency: 0
geom_consistency_regularizer: 0.3
geom_consistency_max_cost: 3
filter: 0
filter_min_ncc: 0.1
filter_min_triangulation_angle: 3
filter_min_num_consistent: 2
filter_geom_consistency_max_cost: 1
write_consistency_graph: 0

PatchMatch::Run
---------------
CUDA error at C:/Users/joschonb/Development/colmap/src/mvs/gpu_mat_ref_image.cu:110 - invalid texture reference
Python: Traceback (most recent call last):
  File "C:\Users\master\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-photogrammetry-master\__init__.py", line 100, in execute
    outputs[p.output].func(load_props, data, scene=scene)
  File "C:\Users\master\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-photogrammetry-master\colmap\load.py", line 246, in load
    raise Exception('Command failed, see system console for details')
Exception: Command failed, see system console for details

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\master\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-photogrammetry-master\__init__.py", line 100, in execute
    outputs[p.output].func(load_props, data, scene=scene)
  File "C:\Users\master\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-photogrammetry-master\colmap\load.py", line 246, in load
    raise Exception('Command failed, see system console for details')
Exception: Command failed, see system console for details

location: <unknown location>:-1

**Comment by stuarta0** [comment]
I also found this error in a project where COLMAP crashes mid-process. I need to investigate further as to why it's occurring.
