### ISSUE TITLE
ImageModeler rzi import issue.

### ISSUE THREAD

**Issue by Colbertson** [stuarta0/blender-photogrammetry#16]
Using version 1.1-linux.
Occasionally some files can't be imported, while others work perfectly fine.
```
Python: Traceback (most recent call last):
  File "/home/colby/.config/blender/2.92/scripts/addons/blender_photogrammetry/__init__.py", line 76, in execute
    data = inputs[p.input].func(extract_props, scene=scene)
  File "/home/colby/.config/blender/2.92/scripts/addons/blender_photogrammetry/imagemodeler/extract.py", line 82, in extract
    f = (float(cinf['fbw']) / 2) / tan(radians(float(intrinsics['fovx']) / 2))
KeyError: 'fbw'

location: <unknown location>:-1
```
Attached is one of the problematic files.
[passat rzi.zip](https://github.com/stuarta0/blender-photogrammetry/files/6258431/passat.rzi.zip)

**Comment by stuarta0** [comment]
Hi @Colbertson. The ImageModeler format is the least supported as I don't actually have a copy myself. I've been reverse engineering the format from a colleagues data. This is what their camera element contains:

```xml
<!-- theirs -->
<CINF i="1" n="Camera"        sw="608"  sh="392"  fbs="c" fbw="37.2245" fovs="v" fovx="56.0062" ds="c" rd="0.05" rstatus="v" hd="0" distoType="disto3i"/>
<!-- yours -->
<CINF i="1" n="Camera Device" sw="2048" sh="1536" fbs="c"               fovs="v" fovx="49.1343"                  rstatus="v" hd="0" distoType="disto3i"/>
```

Note the `fbw` attribute that I'm using as the sensor width combined with `fovx` to calculate the focal length. Your RZI file appears to be missing that attribute. If you can give some insight into the differences within ImageModeler between a file that works and this one I might be able to solve it. e.g. does IM show a different type of camera?

**Comment by AndriyOrlov** [comment]
Traceback (most recent call last):
  File "C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_photogrammetry\__init__.py", line 76, in execute
    data = inputs[p.input].func(extract_props, scene=scene)
  File "C:\Users\Andre\AppData
\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_photogrammetry\imagemodeler\extract.py", line 45, in extract
    co = locator.find('P').attrib
AttributeError: 'NoneType' object has no attribute 'attrib'

location: <unknown location>:-1

[New folder (2).zip](https://github.com/stuarta0/blender-photogrammetry/files/11364951/New.folder.2.zip)
